### ISSUE TITLE
Suggestion modification de l'URL

### ISSUE THREAD

**Issue by D0riane** [Relais4x100a2/velib#3]
Afin d'avoir la date et l'heure de Paris, je propose une légère modification de l'URL pour la requête :

https://opendata.paris.fr/api/records/1.0/search/?dataset=velib-disponibilite-en-temps-reel&q=&facet=name&facet=is_installed&facet=is_renting&facet=is_returning&facet=nom_arrondissement_communes&geofilter.distance=48.8673316%2C2.3374734%2C{}&timezone=Europe%2FParis

**Comment by Relais4x100a2** [comment]
J'ai fait les modifs en créant une sous-branche rendre_velib_duedate.
J'ai fait un pull-request. 
Si ça te va @D0riane , tu peux faire la merge-request
